---
mysql_debian_pkgs_default:
  - python3-mysqldb
mysql_release_specific_debian_pkgs:
  xenial:
    - python-mysqldb
  bionic:
    - python-mysqldb
  focal:
    - python3-mysqldb
mysql_debian_pkgs: "{{ mysql_debian_pkgs_default + mysql_release_specific_debian_pkgs[ansible_distribution_release] }}"


mysql_dir: /etc/mysql

mysql_socket: /var/run/mysqld/mysqld.sock

mysql_server_8_0_pkgs:
   - mysql-client-8.0
   - mysql-client-core-8.0
   - mysql-common
   - mysql-server-8.0
   - mysql-server-core-8.0

DEFAULT_MYSQL_CHARACTER_SET: utf8
DEFAULT_MYSQL_COLLATION: utf8_general_ci

