MONGO_VERSION_MAJOR_MINOR: "7.0"
MONGO_VERSION_PATCH: "8"
PYMONGO_VERSION: "3.12.3"
MONGO_VERSION: "{{ MONGO_VERSION_MAJOR_MINOR }}.{{ MONGO_VERSION_PATCH }}"
mongo_port: "27017"



MONGODB_REPO: "deb http://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/{{ MONGO_VERSION_MAJOR_MINOR }} multiverse"

mongodb_debian_pkgs:
  - "mongodb-org={{ MONGO_VERSION }}"
  - "mongodb-org-server={{ MONGO_VERSION }}"
  - "mongodb-org-shell={{ MONGO_VERSION }}"
  - "mongodb-org-mongos={{ MONGO_VERSION }}"
  - "mongodb-org-tools={{ MONGO_VERSION }}"


# Vars Meant to be overridden
MONGO_ADMIN_USER: 'admin'
MONGO_ADMIN_PASSWORD: 'password'

MONGO_BIND_IP: 127.0.0.1

MONGO_AUTH: true


